import type { Metadata } from 'next'

export function pageMetadata(title: string): Metadata {
  return {
    title: `${title} | Inova Sistemas`,
    description: 'Generated by create next app',
  }
}
